{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoError","stack":"MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/motern/github/parse-node/demo/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:189:7)\n    at Connection.<anonymous> (/Users/motern/github/parse-node/demo/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:291:19)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:192:7)\n    at Socket.<anonymous> (/Users/motern/github/parse-node/demo/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Object.onceWrapper (events.js:291:19)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:189:7)\n    at emitErrorNT (net.js:1280:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)","level":"warn","timestamp":"2017-12-25T01:19:18.381Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoError","stack":"MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/motern/github/parse-node/demo/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:189:7)\n    at Connection.<anonymous> (/Users/motern/github/parse-node/demo/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:291:19)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:192:7)\n    at Socket.<anonymous> (/Users/motern/github/parse-node/demo/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Object.onceWrapper (events.js:291:19)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:189:7)\n    at emitErrorNT (net.js:1280:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)","level":"warn","timestamp":"2017-12-25T01:19:18.383Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoError","stack":"MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/motern/github/parse-node/demo/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:189:7)\n    at Connection.<anonymous> (/Users/motern/github/parse-node/demo/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:291:19)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:192:7)\n    at Socket.<anonymous> (/Users/motern/github/parse-node/demo/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Object.onceWrapper (events.js:291:19)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:189:7)\n    at emitErrorNT (net.js:1280:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)","level":"warn","timestamp":"2017-12-25T01:19:18.383Z"}
